"""Module containing the Visualizer Element class and common primitive subclasses."""

from __future__ import annotations

from typing import Any

from svgwrite import Drawing
from svgwrite.base import BaseElement
from svgwrite.shapes import Rect
from svgwrite.text import Text


class Visualizer_Element:
    """Super class for all visualizer element wrappers that support coordinate checking and transformation.

    Attributes:
        parent (Visualizer_Element | None): The optional parent element of this element used to find global coordinate position.
    """

    def __init__(self, x: int, y: int, name: str):
        self._svg_element: BaseElement | None = None
        self._x: int = x
        self._y: int = y
        self._name: str = name
        self.parent: Visualizer_Element | None = None

    @property
    def name(self) -> str:
        """
        Returns:
            str: The unique name of this element. This will match the id of the svg element being wrapped.
        """
        return self._name

    @property
    def svg_element(self) -> BaseElement:
        """
        If an SVG element has not been generated yet, it will be generated during this call.
        Otherwise, the element that was already generated will be returned.

        Returns:
            BaseElement: The SVG element wrapped by this class.
        """
        if self._svg_element is None:
            self._build_svg_element()
            assert self._svg_element is not None
        return self._svg_element

    @property
    def x(self) -> int:
        """
        Returns:
            int: The x coordinate of this element relative to its parent (or globally).
        """
        return self._x

    @property
    def y(self) -> int:
        """
        Returns:
            int: THe y coordinate of this element relative to its parent (or globally).
        """
        return self._y

    @property
    def global_x(self) -> int:
        """
        Returns:
            int: The global x coordinate of this element based on its parent's coordinates.
        """
        if self.parent is None:
            return self.x
        else:
            return self.parent.global_x + self.x

    @property
    def global_y(self) -> int:
        """
        Returns:
            int: The global y coordinate of this element based on its parent's coordinates.
        """
        if self.parent is None:
            return self.y
        else:
            return self.parent.global_y + self.y

    def _build_svg_element(self) -> None:
        """
        Generates the SVG element generated by this wrapper class and sets it as the svg_element attribute.
        """
        raise NotImplementedError("Implement in base class")

    def relative_position(self, x: int = 0, y: int = 0, relative_to_global: bool = True) -> tuple[int, int]:
        """
        Args:
            x (int, optional): Relative position along the x-axis. Defaults to 0.
            y (int, optional): Relative position along the y-axis. Defaults to 0.
            relative_to_global (bool, optional): If True, returns the relative position to this object's global coordinates. Otherwise, relative to its relative coordinates. Defaults to True.

        Returns:
            tuple[int, int]: The global x,y coordinate relative to this element by the given values.
        """
        if relative_to_global:
            return self.global_x + x, self.global_y + y
        else:
            return self.x + x, self.y + y

    def add_to_drawing(self, drawing: Drawing) -> None:
        """
        Adds this element to the given svg drawing.
        Args:
            drawing (Drawing): The drawing to add.
        """
        drawing.add(self.svg_element)

    def __str__(self) -> str:
        return self.name

    def __repr__(self) -> str:
        return str(self)

    def __hash__(self) -> int:
        return hash(self.name)


class Text_Element(Visualizer_Element):
    """
    Wrapper class for Text SVG elements.
    """

    def __init__(self, x: int, y: int, label: str, name: str | None = None, **text_kwargs: Any) -> None:
        """
        Initialize the text element.
        Args:
            x (int): The x coordinate of this element relative to its parent (or globally).
            y (int): The y coordinate of this element relative to its parent (or globally).
            label (str): The value of the text label.
            name (str, optional): The id name of this element defaults to "label_<label>".
            **text_kwargs (Any): Keyword arguments used to configure the svg text element.
        """
        super().__init__(x, y, name if name is not None else f"label_{label}")
        self._text_kwargs: dict[str, Any] = text_kwargs
        self.label: str = label

    def _build_svg_element(self) -> None:
        self._svg_element = Text(self.label, insert=(self.global_x, self.global_y), id=self.name, **self._text_kwargs)


class Rect_Element(Visualizer_Element):
    """
    Wrapper class for Rectangle SVG elements.

    Attributes:
        width (int): The width of the rectangle.
        height (int): The height of the rectangle.
    """

    def __init__(self, x: int, y: int, name: str, width: int, height: int, **rect_kwargs: Any) -> None:
        """
        Initialize the Rectangle SVG element.

        Args:
            x (int): The x coordinate of the rectangle element relative to its parent.
            y (int): The y coordinate of the rectangle element relative to its parent.
            name (str): The name of the rectangle element used as the element id.
            width (int): The width of the rectangle in pixels.
            height (int): The height of the rectangle in pixels.
            **rect_kwargs (Any): The keyword elements to pass to configure the Rect SVG element.
        """
        super().__init__(x, y, name)
        self._rect_kwargs: dict[str, Any] = rect_kwargs
        self.width: int = width
        self.height: int = height

    def _build_svg_element(self) -> None:
        self._svg_element = Rect(
            insert=(self.global_x, self.global_y), id=self.name, size=(self.width, self.height), **self._rect_kwargs
        )
