"""Module containing the Visualizer Element class and common primitive subclasses."""

from __future__ import annotations

from typing import Any

from svgwrite import Drawing
from svgwrite.base import BaseElement
from svgwrite.shapes import Circle, Rect
from svgwrite.text import Text


class Visualizer_Element:
    """Super class for all visualizer element wrappers that support coordinate checking and transformation.

    Attributes:
        parent (Visualizer_Element | None): The optional parent element of this element used to find global coordinate position.
    """

    def __init__(self, x: int, y: int, name: str):
        self._svg_element: BaseElement | None = None
        self._x: int = x
        self._y: int = y
        self._name: str = name
        self.parent: Visualizer_Element | None = None

    @property
    def name(self) -> str:
        """
        Returns:
            str: The unique name of this element. This will match the id of the svg element being wrapped.
        """
        return self._name

    @property
    def x(self) -> int:
        """
        Returns:
            int: The x coordinate of this element relative to its parent (or globally).
        """
        return self._x

    @property
    def y(self) -> int:
        """
        Returns:
            int: THe y coordinate of this element relative to its parent (or globally).
        """
        return self._y

    @property
    def global_x(self) -> int:
        """
        Returns:
            int: The global x coordinate of this element based on its parent's coordinates.
        """
        if self.parent is None:
            return self.x
        else:
            return self.parent.global_x + self.x

    @property
    def global_y(self) -> int:
        """
        Returns:
            int: The global y coordinate of this element based on its parent's coordinates.
        """
        if self.parent is None:
            return self.y
        else:
            return self.parent.global_y + self.y

    def global_x_position(self, x: int) -> int:
        """
        Args:
            x (int): An X-coordinate position relative to this element's coordinate system.

        Returns:
            int: The x-coordinate adjusted to the global coordinate system.
        """
        return self.global_x + x

    def global_y_position(self, y: int) -> int:
        """
        Args:
            y (int): An Y-coordinate position relative to this element's coordinate system.

        Returns:
            int: The y-coordinate adjusted to the global coordinate system.
        """
        return self.global_y + y

    def _build_svg_element(self) -> BaseElement:
        """
        Generates the SVG element generated by this wrapper class.

        Returns:
            BaseElement: The generated SVG element for this wrapper class.
        """
        raise NotImplementedError("Implement in base class")

    def add_to_drawing(self, drawing: Drawing) -> None:
        """
        Adds this element to the given svg drawing.
        Args:
            drawing (Drawing): The drawing to add.
        """
        drawing.add(self._build_svg_element())

    def __str__(self) -> str:
        return self.name

    def __repr__(self) -> str:
        return str(self)

    def __hash__(self) -> int:
        return hash(self.name)

    @staticmethod
    def darken_color(color: str, factor: float = 0.7) -> str:
        """Darken a hex or named color.
        Args:
            color (str): The color to darken. May be a named color or a hex representation of the color.
            factor (float, optional): A factor to darken. Defaults to 0.7.

        Returns:
            str: The hex value string of the darkened color.
        """
        # Handle named colors
        if not color.startswith("#"):
            try:
                import webcolors

                color = webcolors.name_to_hex(color)
            except (ImportError, ValueError):
                # Fallback: assume it's already valid
                pass

        # Rest of your darkening code...
        color = color.lstrip("#")
        r = int(int(color[0:2], 16) * factor)
        g = int(int(color[2:4], 16) * factor)
        b = int(int(color[4:6], 16) * factor)
        return f"#{r:02x}{g:02x}{b:02x}"


class Text_Element(Visualizer_Element):
    """
    Wrapper class for Text SVG elements.
    """

    def __init__(self, x: int, y: int, label: str, name: str | None = None, **text_kwargs: Any) -> None:
        """
        Initialize the text element.
        Args:
            x (int): The x coordinate of this element relative to its parent (or globally).
            y (int): The y coordinate of this element relative to its parent (or globally).
            label (str): The value of the text label.
            name (str, optional): The id name of this element defaults to "label_<label>".
            **text_kwargs (Any): Keyword arguments used to configure the svg text element.
        """
        super().__init__(x, y, name if name is not None else f"label_{label}")
        self._text_kwargs: dict[str, Any] = text_kwargs
        self.label: str = label

    def _build_svg_element(self) -> Text:
        return Text(self.label, insert=(self.global_x, self.global_y), id=self.name, **self._text_kwargs)


class Rect_Element(Visualizer_Element):
    """
    Wrapper class for Rectangle SVG elements.

    Attributes:
        width (int): The width of the rectangle.
        height (int): The height of the rectangle.
    """

    def __init__(self, x: int, y: int, name: str, width: int, height: int, **rect_kwargs: Any) -> None:
        """
        Initialize the Rectangle SVG element.

        Args:
            x (int): The x coordinate of the rectangle element relative to its parent.
            y (int): The y coordinate of the rectangle element relative to its parent.
            name (str): The name of the rectangle element used as the element id.
            width (int): The width of the rectangle in pixels.
            height (int): The height of the rectangle in pixels.
            **rect_kwargs (Any): The keyword elements to pass to configure the Rect SVG element.
        """
        super().__init__(x, y, name)
        self._rect_kwargs: dict[str, Any] = rect_kwargs
        self.width: int = width
        self.height: int = height

    def _build_svg_element(self) -> Rect:
        return Rect(
            insert=(self.global_x, self.global_y), id=self.name, size=(self.width, self.height), **self._rect_kwargs
        )


class Circle_Element(Visualizer_Element):
    """
    Wrapper class for Circle SVG elements.

    Attributes:
        radius (int): The radius of the circle.
    """

    def __init__(self, x: int, y: int, name: str, radius: int, auto_darken_stroke: bool = True, **circle_kwargs: Any):
        """
        Initialize the Circle SVG element.

        Args:
            x (int): The x coordinate of the circle's center relative to its parent.
            y (int): The y coordinate of the circle's center relative to its parent.
            name (str): The name of the circle element used as the element id.
            radius (int): The radius of the circle in pixels.
            auto_darken_stroke (bool, optional): If True, a stroke color will be derived from any fill parameter in the circle keyword arguments. Defaults to True.
            **circle_kwargs (Any): The keyword elements to pass to configure the Circle SVG element.
        """
        super().__init__(x, y, name)
        self._circle_kwargs: dict[str, Any] = circle_kwargs
        if auto_darken_stroke and "fill" in self._circle_kwargs and self._circle_kwargs["fill"] != "none":
            self._circle_kwargs["stroke"] = self.darken_color(self._circle_kwargs["fill"])
        self.radius: int = radius

    def _build_svg_element(self) -> Circle:
        return Circle(center=(self.global_x, self.global_y), id=self.name, r=self.radius, **self._circle_kwargs)
